
#
# Create the private zone first
#

- name: Create DNS zone for openshift
  route53_zone:
     zone: "{{ namespace }}.local"
     state: "present"
     vpc_id: "{{vpc_id}}"
     vpc_region: "{{ region }}"
     comment: "Internal zone for {{ namespace }}"
  register: aws_zone

#
# Masters
#

- name: Add private master A record (e.g. master.ocp.local)
  route53:
    zone: "{{ namespace }}.local"
    record: "master.{{ namespace }}.local"
    type: A
    ttl: 300
    value: "{{ all_master_nodes|map(attribute='private_ip')|join(',') }}"
    vpc_id: "{{vpc_id}}"
    private_zone: true
    command: "create"
    overwrite: yes

- name: Add public master A record (e.g. master.ocp.example.com)
  route53:
    zone: "{{public_dns_zone}}"
    record: "master.{{ namespace }}.{{public_dns_zone}}"
    type: A
    ttl: 300
    value: "{{ all_master_nodes|map(attribute='public_ip')|join(',') }}"
    command: "create"
    overwrite: yes
  when: master_nodes == 1

- name: Add public master A record (e.g. master.ocp.example.com)
  route53:
    zone: "{{public_dns_zone}}"
    record: "master.{{ namespace }}.{{public_dns_zone}}"
    type: A
    ttl: 300
    value: "{{ router_public_ip }}"
    command: "create"
    overwrite: yes
  when: master_nodes > 1

- name: Add private master A records (e.g. master1.ocp.local)
  route53:
    zone: "{{ namespace }}.local"
    record: "master{{item.index}}.{{ namespace }}.local"
    type: A
    ttl: 300
    value: "{{item.private_ip}}"
    vpc_id: "{{vpc_id}}"
    private_zone: true
    command: "create"
    overwrite: yes
  with_items: "{{ all_master_nodes }}"

#
# Application nodes
#

- name: Add private app node A records (e.g. app1.ocp.local)
  route53:
    zone: "{{ namespace }}.local"
    record: "app{{item.index}}.{{ namespace }}.local"
    type: A
    ttl: 300
    value: "{{item.private_ip}}"
    vpc_id: "{{vpc_id}}"
    private_zone: true
    command: "create"
    overwrite: yes
  with_items: "{{ all_app_nodes }}"

#
# Infra nodes
#

- name: Add private infra node A records (e.g. infra1.ocp.local)
  route53:
    zone: "{{ namespace }}.local"
    record: "infra{{item.index}}.{{ namespace }}.local"
    type: A
    ttl: 300
    value: "{{item.private_ip}}"
    vpc_id: "{{vpc_id}}"
    private_zone: true
    command: "create"
    overwrite: yes
  with_items: "{{ all_infra_nodes }}"
  when: infra_nodes > 0

#
# Ingress point for apps running on the cluster
#

- name: Add public wildcard A record, mapped to masters (e.g. *.apps.ocp.example.com)
  route53:
    zone: "{{public_dns_zone}}"
    record: "*.{{public_subdomain_prefix}}.{{ namespace }}.{{public_dns_zone}}"
    type: A
    ttl: 300
    value: "{{ all_master_nodes|map(attribute='public_ip')|join(',') }}"
    command: "create"
    overwrite: yes
    wait: yes
  when: infra_nodes == 0

- name: Add public wildcard A record, mapped to infra nodes (e.g. *.apps.ocp.example.com)
  route53:
    zone: "{{public_dns_zone}}"
    record: "*.{{public_subdomain_prefix}}.{{ namespace }}.{{public_dns_zone}}"
    type: A
    ttl: 300
    value: "{{ all_infra_nodes|map(attribute='public_ip')|join(',') }}"
    command: "create"
    overwrite: yes
    wait: yes
  when: infra_nodes > 0

# Keep the 'wait' attribute on the last DNS operation to give Route53 some time to replicate all updated setting before we move on.