
- name: Add public master A record (e.g. master.ocp.example.com)
  route53:
    zone: "{{public_dns_zone}}"
    record: "master.{{ namespace }}.{{public_dns_zone}}"
    type: A
    ttl: 300
    value: "{{ all_master_nodes|map(attribute='public_ip')|join(',') }}"
    command: "create"
    overwrite: yes

- name: Add public wildcard A record, mapped to infra nodes (e.g. *.apps.ocp.example.com)
  route53:
    zone: "{{public_dns_zone}}"
    record: "*.{{public_subdomain_prefix}}.{{ namespace }}.{{public_dns_zone}}"
    type: A
    ttl: 300
    value: "{{ all_infra_nodes|map(attribute='public_ip')|join(',') }}"
    command: "create"
    overwrite: yes
    wait: yes

# Keep the 'wait' attribute on the last DNS operation to give Route53 some time to replicate all updated setting before we move on.