
- name: List all hosted zones
  route53_facts:
    query: hosted_zone
  register: hosted_zones
  
- name: Delete public wildcard route (e.g. apps.ocp.example.com)
  include: delete-route.yml zone="{{ public_dns_zone }}" record="apps.{{ namespace }}.{{ public_dns_zone }}" private_zone="false"
  wait: yes
  ignore_errors: true

- name: Delete public wildcard route (e.g. *.svc.ocp.example.com)
  include: delete-route.yml zone="{{ public_dns_zone }}" record="*.{{ public_subdomain_prefix }}.{{ namespace }}.{{ public_dns_zone }}" private_zone="false"
  wait: yes
  ignore_errors: true

- name: Delete public master route (e.g. master.ocp.example.com)
  include: delete-route.yml zone="{{ public_dns_zone }}" record="master.{{ namespace }}.{{ public_dns_zone }}" private_zone="false"
  wait: yes
  ignore_errors: true


