
- name: Install OpenShift
  hosts: localhost
  roles:
    - role: ../../roles/get_availability_zone
    - role: ../../roles/get_vpc_facts
    - role: ../../roles/get_node_facts
    - role: ../../roles/configure_inventory
    - role: ../../roles/provision_openshift
