
# This security group allows intra-node communication on all ports with all protocols.
- name: Create intra-node security group
  ec2_group:
    name: "{{ namespace }}_internal"
    description: "Default security group that allows all instances in the VPC to talk to each other over any port and protocol."
    vpc_id: "{{vpc_id}}"
    region: "{{ region }}"
    state: "present"
    rules:
      - proto: "-1"
        from_port: "0"
        to_port: "0"
        group_name: "{{ namespace }}_internal"
    rules_egress:
      - proto: "-1"
        from_port: "0"
        to_port: "0"
        group_name: "{{ namespace }}_internal"

# Security group which allows SSH access to bastion and all egress.
- name: Create SSH security group
  ec2_group:
    name: "{{ namespace }}_ssh"
    description: "Default security group that allows ssh access to the instance"
    vpc_id: "{{vpc_id}}"
    region: "{{ region }}"
    state: "present"
    rules:
      - proto: "tcp"
        from_port: "22"
        to_port: "22"
        cidr_ip: "0.0.0.0/0"
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
        
#  This security group allows public ingress to the instances for HTTP, HTTPS and common HTTP/S proxy ports.
- name: Create public-ingress security group
  ec2_group:
    name: "{{ namespace }}_public_ingress"
    description: "Security group that allows public ingress to instances, HTTP, HTTPS and more."
    vpc_id: "{{vpc_id}}"
    region: "{{ region }}"
    state: "present"
    rules:
      # HTTP
      - proto: "tcp"
        from_port: "80"
        to_port: "80"
        cidr_ip: "0.0.0.0/0"
      # HTTP_PROXY
      - proto: "tcp"
        from_port: "8080"
        to_port: "8080"
        cidr_ip: "0.0.0.0/0"
      # HTTPS
      - proto: "tcp"
        from_port: "443"
        to_port: "443"
        cidr_ip: "0.0.0.0/0"
      # HTTPS_PROXY
      - proto: "tcp"
        from_port: "8443"
        to_port: "8443"
        cidr_ip: "0.0.0.0/0"
      # Cockpit
      - proto: "tcp"
        from_port: "9090"
        to_port: "9090"
        cidr_ip: "0.0.0.0/0"
    rules_egress: []    
 
#  This security group allows public ingress to the instances for HTTP, HTTPS and common HTTP/S proxy ports.
- name: Create public-egress security group
  ec2_group:
    name: "{{ namespace }}_public_egress"
    description: "This security group allows public egress from the instances for HTTP and HTTPS, which is needed for yum updates, git access etc etc."
    vpc_id: "{{vpc_id}}"
    region: "{{ region }}"
    state: "present"
    rules_egress:
      # HTTP
      - proto: "tcp"
        from_port: "80"
        to_port: "80"
        cidr_ip: "0.0.0.0/0"
      # HTTPS
      - proto: "tcp"
        from_port: "443"
        to_port: "443"
        cidr_ip: "0.0.0.0/0"
      - proto: "tcp"
        from_port: "8443"
        to_port: "8443"
        cidr_ip: "0.0.0.0/0"
