
#  This security group allows public ingress to the instances for HTTP, HTTPS and common HTTP/S proxy ports.
- name: Create public-ingress security group
  ec2_group:
    name: "{{ namespace }}_public_ingress"
    description: "Security group that allows public ingress to instances, HTTP, HTTPS and more."
    vpc_id: "{{vpc_id}}"
    region: "{{ region }}"
    state: "present"
    rules:
      # HTTP
      - proto: "tcp"
        from_port: "80"
        to_port: "80"
        cidr_ip: "0.0.0.0/0"
      # HTTP_PROXY
      - proto: "tcp"
        from_port: "8080"
        to_port: "8080"
        cidr_ip: "0.0.0.0/0"
      # HTTPS
      - proto: "tcp"
        from_port: "443"
        to_port: "443"
        cidr_ip: "0.0.0.0/0"
      # HTTPS_PROXY
      - proto: "tcp"
        from_port: "8443"
        to_port: "8443"
        cidr_ip: "0.0.0.0/0"
      # Cockpit
      - proto: "tcp"
        from_port: "9090"
        to_port: "9090"
        cidr_ip: "0.0.0.0/0"
    rules_egress: []    
 
#  This security group allows public ingress to the instances for HTTP, HTTPS and common HTTP/S proxy ports.
- name: Create public-egress security group
  ec2_group:
    name: "{{ namespace }}_public_egress"
    description: "This security group allows public egress from the instances for HTTP and HTTPS, which is needed for yum updates, git access etc etc."
    vpc_id: "{{vpc_id}}"
    region: "{{ region }}"
    state: "present"
    rules_egress:
      # HTTP
      - proto: "tcp"
        from_port: "80"
        to_port: "80"
        cidr_ip: "0.0.0.0/0"
      # HTTPS
      - proto: "tcp"
        from_port: "443"
        to_port: "443"
        cidr_ip: "0.0.0.0/0"
      - proto: "tcp"
        from_port: "8443"
        to_port: "8443"
        cidr_ip: "0.0.0.0/0"
