
- name: Find AMI
  ec2_ami_facts:
    region: "{{ region }}"
    filters:
      "tag:Name": "{{ ami_name }}"
  register: "ami_find"

- include_tasks: create-masters.yml

- include_tasks: create-app-nodes.yml

- include_tasks: create-infra-nodes.yml
  when: infra_nodes > 0

- include_tasks: create-router-node.yml
  when: master_nodes > 1

- include_tasks: create-host-groups.yml

- name: Wait for masters SSH to come up
  wait_for:
    host: '{{ item.public_ip }}'
    port: 22
    state: started
  with_items:
    - "{{ all_master_nodes }}"

- name: Wait for app node SSH to come up
  wait_for:
    host: '{{ item.public_ip }}'
    port: 22
    state: started
  with_items:
    - "{{ all_app_nodes }}"

- name: Wait for infra node SSH to come up
  wait_for:
    host: '{{ item.public_ip }}'
    port: 22
    state: started
  with_items:
    - "{{ all_infra_nodes }}"
  when: infra_nodes > 0