
- name: Find Node AMI
  ec2_ami_facts:
    region: "{{ region }}"
    filters:
      "tag:Name": "{{ ami_name }}_node"
  register: "node_ami_find"

- name: Find Bastion AMI
  ec2_ami_facts:
    region: "{{ region }}"
    filters:
      "tag:Name": "{{ ami_name }}_bastion"
  register: "bastion_ami_find"

- include_tasks: create-app-nodes.yml

- include_tasks: create-infra-nodes.yml

- include_tasks: create-masters.yml

- include_tasks: create-bastion.yml

- name: Wait for SSH to come up
  wait_for:
    host: '{{ item }}'
    port: 22
    delay: 60
    timeout: 300
    state: started
  with_items:
    - "{{ bastion_public_ip }}"
