
- name: Gather EC2 facts
  ec2_instance_facts:
    region: "{{ region }}"
    filters:
      "tag:namespace": "{{ namespace }}"
  register: ec2_facts

- name: Register facts
  set_fact:
    availability_zone: "{{ ec2_facts['instances'][0]['placement']['availability_zone'] }}"

- name: Copy ansible.cfg
  template:
    src: "../files/ansible.cfg"
    dest: "~{{ instance_user }}/ansible.cfg"
    mode: "0775"
  delegate_to: "bastion.{{ namespace }}.{{ public_dns_zone }}"
  remote_user: "{{ instance_user }}"

- name: Copy scripts for OpenShift installation
  template:
    src: "../files/provision.sh"
    dest: "~{{ instance_user }}/provision.sh"
    mode: "0775"
  delegate_to: "bastion.{{ namespace }}.{{ public_dns_zone }}"
  remote_user: "{{ instance_user }}"
  
- name: Create the inventory
  template:
    src: "../files/inventory_template.cfg"
    dest: "~{{ instance_user }}/inventory"
  delegate_to: "bastion.{{ namespace }}.{{ public_dns_zone }}"
  remote_user: "{{ instance_user }}"