
- name: Checkout openshift-ansible playbooks
  git:
    repo: "https://github.com/openshift/openshift-ansible"
    dest: "~{{ instance_user }}/openshift-ansible"
    version: "{{ openshift_ansible_branch }}"
  delegate_to: "bastion.{{ namespace }}.{{ public_dns_zone }}"
  remote_user: "{{ instance_user }}"

- name: Copy ansible.cfg
  template:
    src: "../files/ansible.cfg"
    dest: "~{{ instance_user }}/ansible.cfg"
    mode: "0775"
  delegate_to: "bastion.{{ namespace }}.{{ public_dns_zone }}"
  remote_user: "{{ instance_user }}"

- name: Copy scripts for OpenShift installation
  template:
    src: "../files/provision.sh"
    dest: "~{{ instance_user }}/provision.sh"
    mode: "0775"
  delegate_to: "bastion.{{ namespace }}.{{ public_dns_zone }}"
  remote_user: "{{ instance_user }}"
  
- name: Create the inventory
  template:
    src: "../files/inventory_template.cfg"
    dest: "~{{ instance_user }}/inventory"
  delegate_to: "bastion.{{ namespace }}.{{ public_dns_zone }}"
  remote_user: "{{ instance_user }}"