
- name: Teardown Instances
  hosts: localhost
  gather_facts: false
  roles:
    - role: ../../roles/get_vpc_facts
    - role: ../../roles/deprovision_instances
    - role: ../../roles/deprovision_bastion
