
- name: Provision Cluster
  hosts: localhost
  gather_facts: false
  roles:
    - role: ../../roles/get_vpc_facts
    - role: ../../roles/create_bastion
    - role: ../../roles/create_instances
    - role: ../../roles/create_dns
    - role: ../../roles/create_ssh
    - role: ../../roles/create_host_groups

- name: Configure Cluster
  hosts: created_instances
  gather_facts: false
  vars:
    state: 'present'
  roles:
    - ../../roles/get_availability_zone
    - ../../roles/configure_instances
  remote_user: "{{ instance_user }}"
