
- name: Provision Cluster
  hosts: localhost
  gather_facts: false
  roles:
    - role: ../../roles/get_vpc_facts
    - role: ../../roles/create_instances
    - role: ../../roles/create_host_groups
    - role: ../../roles/create_dns
    - role: ../../roles/create_ssh

- name: Gather facts
  hosts: localhost
  gather_facts: false
  roles:
    - role: ../../roles/get_availability_zone

- name: Configure Cluster
  hosts: created_instances
  gather_facts: false
  vars:
    state: 'present'
  roles:
    - ../../roles/configure_instances
  remote_user: "{{ instance_user }}"
