
- name: Gather facts
  ec2_remote_facts:
    region: "{{ region }}"
    filters:
      "tag:namespace": "{{ namespace }}"
      "tag:group": "cluster"
  register: ec2_facts

- name: Stop all instances
  ec2:
    state: stopped
    region: "{{ region }}"
    instance_ids: "{{ item.id }}"
    wait: yes
  with_items: "{{ ec2_facts.instances }}"
  when: item.state == 'running'