
# WARNING: THIS DELETES ALL INSTANCES AND VOLUMES. TOTAL WIPE-OUT. YOU HAVE BEEN WARNED!.

- name: Gather EC2 facts
  ec2_instance_facts:
    region: "{{ region }}"
    filters:
      "tag:namespace": "{{ namespace }}"
      "tag:group": "cluster"
  register: ec2_facts

- name: Terminate EC2 VMs
  ec2:
    state: absent
    region: "{{ region }}"
    instance_ids: "{{ item.instance_id }}"
    wait: yes
  with_items: "{{ ec2_facts.instances }}"
  when: item.state != 'terminated'

# In OCP 3.7 volumes are tagged using the kube cluster tag
# so we can be sure we are deleting volumes belonging to the
# cluster we are tearing down
- name: Retrieve dynamic volumes
  ec2_vol_facts:
    region: "{{ region }}"
    filters:
        "{'tag:kubernetes.io/cluster/{{ namespace }}':'owned','status':'available'}"
  register: aws_volumes

- debug:
    msg: "{{aws_volumes}}"

- name: Delete dynamic volumes
  ec2_vol:
    region: "{{ region }}"
    state: "absent"
    id: "{{item.id}}"
  with_items: "{{aws_volumes.volumes}}"