
- ec2_vpc_net_facts:
    region: "{{ region }}"
    filters:
      "tag:Name": "{{ vpc_name }}"
  register: vpc_facts

- ec2_vpc_subnet_facts:
    region: "{{ region }}"
    filters:
      "tag:Name": "{{ vpc_name }}_subnet"
  register: subnet_facts

- name: Register facts
  set_fact:
    vpc_id: "{{ vpc_facts['vpcs'][0]['id'] }}"
    subnet_id: "{{ subnet_facts['subnets'][0]['id'] }}"
